/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ui: {
          surface: 'var(--surface)',
          muted: 'var(--surface-muted)',
          hover: 'var(--surface-hover)',
          line: 'var(--line)',
          lineStrong: 'var(--line-strong)',
          text: 'var(--text)',
          textMuted: 'var(--text-muted)',
          textSoft: 'var(--text-soft)',
          primary: 'var(--brand-primary)',
          primaryStrong: 'var(--brand-primary-strong)',
          primaryDark: 'var(--brand-primary-dark)',
          primarySoft: 'var(--brand-primary-soft)',
          successSoft: 'var(--status-success-bg)',
          successText: 'var(--status-success-text)',
          warningSoft: 'var(--status-warning-bg)',
          warningText: 'var(--status-warning-text)',
          dangerSoft: 'var(--status-danger-bg)',
          dangerText: 'var(--status-danger-text)',
          infoSoft: 'var(--status-info-bg)',
          infoText: 'var(--status-info-text)',
        },
        brand: {
          dark: '#10213f',
          ink: '#132039',
          orange: '#f17e22',
          orangeStrong: '#e86f16',
          orangeSoft: '#fff0e4',
          teal: '#0ea78b',
          tealDark: '#1e605e',
          canvas: '#f6f8fb',
          line: '#dde6f1',
        },
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        card: 'var(--shadow-card)',
        hero: 'var(--shadow-hero)',
        tenant: 'var(--shadow-card)',
        brand: 'var(--shadow-primary-hover)',
      },
      borderRadius: {
        control: 'var(--radius-control)',
        compact: 'var(--radius-compact)',
        card: 'var(--radius-card)',
        hero: 'var(--radius-hero)',
        tenant: 'var(--radius-control)',
      },
      spacing: {
        page: 'var(--page-padding)',
        pageMobile: 'var(--page-padding-mobile)',
        section: 'var(--section-gap)',
        card: 'var(--card-padding)',
        grid: 'var(--grid-gap)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
